check for presence of jq

diff --git a/bin/vscode-extensions b/bin/vscode-extensions
--- a/bin/vscode-extensions
+++ b/bin/vscode-extensions
@@ -1,7 +1,7 @@
 #!/usr/bin/env fish
 # vim:ft=fish
 
-if not command -sq code
+if not command --quiet code
   echo >&2 "error: VS Code not found"
   exit 1
 end
@@ -35,6 +35,10 @@ function do_diff
 end
 
 function do_json
+  if not command --quiet jq
+    echo >&2 'jq not found'
+    return 1
+  end
   set -l jq_script '.recommendations=[$exts|rtrimstr("\n")|split("\n")]'
   echo '{}' | jq --monochrome-output --rawfile exts (do_list | psub) $jq_script
 end
